CREATE TABLE IF NOT EXISTS tanidiklar (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    license1 VARCHAR(64) NOT NULL,
    license2 VARCHAR(64) NOT NULL,
    isim1 VARCHAR(64) NOT NULL,
    isim2 VARCHAR(64) NOT NULL
);
